name: test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        php-version: ["8.1", "8.4"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo_sqlite
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: ./doit.sh
